### ISSUE TITLE
Feature request: turn \href{url}{text} into a proper link

### ISSUE THREAD

**Issue by mamoll** [inukshuk/jekyll-scholar#101]
Perhaps this can be done by modifying `jekyll/scholar/plugins/markdown_links.rb`.

**Comment by inukshuk** [comment]
Good idea! That should be fairly easy -- I can add this right away, but feel free to elaborate on it (or add more tests) if you have a good use case for this.

**Comment by mamoll** [comment]
There are some conferences in my field that allow you submit videos, either as a supplement or as its own submission (in a special category). To differentiate the latter from "regular" submissions, I add a note  like this:
```
   note = {\href{url}{Video}}
```

**Comment by inukshuk** [comment]
This should work already, no? I used the publisher in my test case, but it should work with note just as well.

**Comment by mamoll** [comment]
It doesn't seem to work for me. Look for "Video" on this page: http://www.cs.rice.edu/~mmoll/publications.html

**Comment by inukshuk** [comment]
Just to make sure, you have enabled the markdown filter, right?

**Comment by mamoll** [comment]
Probably not. How do I do that?

**Comment by inukshuk** [comment]
In you config you need something like:

    scholar:
      bibtex_filters:
        - markdown
        - latex

**Comment by mamoll** [comment]
That turns the output into this:
```
W.-M. Shen, B. Salemi, M. Moll, C. H. Chiu, J. Everist, F. Hou, N. Ranasinghe, and M. Rubenstein, “Multifunctional Behaviors of Reconfigurable SuperBot Modules,” in Proc. 2007 IEEE/RSJ Intl. Conf. on Intelligent Robots and Systems, 2007. \href[http://www.isi.edu/robots/superbot/movies/SuperBot.mov](http://www.isi.edu/robots/superbot/movies/SuperBot.mov)Video 
```

**Comment by inukshuk** [comment]
Yes, this is the tricky part of this converter...

Do you have `markdown` in the array? (It could be that the latex filter removes the braces) If that's not it, could you try escaping the braces like I did in the test case here: https://github.com/inukshuk/jekyll-scholar/blob/51ec9fcd79edcbbd9604a864fa0ed6f3df8eaa00/features/filter.feature#L184

**Comment by mamoll** [comment]
I have tried all combinations of those two bibtex filters, with and without escaping of curly braces. I don't see where in the jekyll-scholar code `\href{url}{text}` gets turned into html or markdown. Also, if you start escaping curly braces, then the same bib file can no longer be used by LaTeX. IMHO, that is not a good solution.

**Comment by inukshuk** [comment]
Yes, obviously we don't want to escape the braces, I just wanted to see if that's what was causing the problem.

The braces in the test case I linked to above are probably wrong (I thought they were necessary because of cucumber, but now that I look at it that was a bad call). However, the test works, so that means it should be working for you right now if you escape the braces... once we have that working it is a matter of adjusting the regular expression to work without the escapes.

The filter is [here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/plugins/markdown_links.rb#L15) -- for debugging purposes you can break there or print out the values before the `gsub` and `$1` and `$2` inside.

**Comment by mamoll** [comment]
Part of the problem may be that I was a couple of commits behind. With the latest commit I can get this output:
```
 [Video](http://www.isi.edu/robots/superbot/movies/SuperBot.mov) 
```
I changed the first part of the if statement in the markdown filter:
```
          if $1
            puts $2, $1
            "[#{$2}](#{$1})"
          else
```
and I see that it gets called. I don't understand why the markdown text doesn't get translated to html.

**Comment by inukshuk** [comment]
Ah, that explains it! Do you need to escape the braces now, though?

The output looks correct to me, but it assumes that you are using the respective bibliography tag inside a markdown file -- otherwise the markdown is not further translated to HTML.

It would be trivial to write another filter just like the markdown filter which produces an HTML tag instead. All you need to do is inherit from [BibTeX::Filter](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/plugins/markdown_links.rb#L13) -- the respective class name (downcased) will be the name of the filter. You can put the filter anywhere, e.g., in your `ext.rb` file and add it to your configuration.

**Comment by mamoll** [comment]
Another problem was that I had this in my `_config.yml` file:
```
markdown:      kramdown
kramdown:
    parse_block_html: true
```
Adding this to my `ext.rb` fixes things for me:
```
require 'uri'
require 'jekyll/scholar'

module Jekyll
  class Scholar
    class Href < BibTeX::Filter
      def apply(value)
        value.to_s.gsub(URL_PATTERN) {
          if $1
            "<a href=\"#{$1}\">#{$2}</a>"
          end
        }
      end
    end
  end
end
```
In my `_config.yml` I had to add this:
```
scholar:
    bibtex_filters:
      - href
      - latex
```

**Comment by mamoll** [comment]
It turns out I actually *do* need that kramdown option: I occasionally need to wrap markdown text in some divs. The final solution I arrived that works for with that option enabled and without having to escape curly braces in the bibtex is this code:
```
require 'jekyll/scholar'

HREF_PATTERN = Regexp.compile('\\\\href\\{([^\\}]+)\\}\\{([^\\}]+)\\}')

module Jekyll
  class Scholar
    class Href < BibTeX::Filter
      def apply(value)
        value.to_s.gsub(HREF_PATTERN) {
          if $1
            "<a href=\"#{$1}\">#{$2}</a>"
          end
        }
      end
    end
  end
end
```
(Settings in `_config.tml` as described above.) Do with this what you want. The ticket can be closed as far as I am concerned.

**Comment by inukshuk** [comment]
Just a minor detail: you can skip the `if $1` part, because if your pattern matches, the capture groups definitely exist.

Also you should move the `HREF_PATTERN` constant into the `Href` class so as not to pollute the global namespace (we need to do that for the markdown filter, too, my bad!).
