### ISSUE TITLE
defaults.rb ignored by jekyll

### ISSUE THREAD

**Issue by kristiannordestgaard** [inukshuk/jekyll-scholar#125]
I am unsure if this is a jekyll-scholar issue or if it has to do with jekyll itself, please excuse me if it is the latter. 

I made a directory called `_plugins` and put `defaults.rb` in it, but it is ignored. I also put `plugins-dir: _plugins` in `_config.yml`, but nothing happens. What could the problem be?

**Comment by kristiannordestgaard** [comment]
Oh, and I'm on `jekyll 3.1.0` and `jekyll-scholar (5.5.0)` so everything should be up to date.

**Comment by inukshuk** [comment]
Well, this would definitely be a jekyll issue... but this is so fundamental that I can't imagine it's an actual bug, but rather some configuration/environment issue on your end? Jekyll should just load every *.rb file in the `_plugins`. Maybe you're re-defining `plugins-dir` later on in your config file? I'd try to start with a pristine jekyll setup, ensure that your file is loaded there, then incrementally add the rest of your site to find the source of the problem.

**Comment by kristiannordestgaard** [comment]
Thanks, and pardons if the problem is with Jekyll (or, more likely, me.) 

I think I got it running, per your instructions. What I need to do is have the `url` field ignored. I have `'bibtex_skip_fields'     => [ :abstract, :month_numeric, :url ],` in `defaults.rb` but the URLs still get parsed. How can I fix this?

**Comment by inukshuk** [comment]
Ah, well this configuration should go into your `_config.yml` -- files in `_plugins` get parsed, but they don't magically turn up in the jekyll configuration. What you could do is change jekyll-scholar's defaults (I guess this is what you are trying to do) by setting:

`Jekyll::Scholar.defaults['bibtex_skip_fields'] = [:abstract, :month_numeric, :url]`

If you do that you probably also need to `require 'jekyll/scholar'` first to make sure it is already loaded.

**Comment by kristiannordestgaard** [comment]
Thanks. Please tell me exactly where to put which lines, I can't get it to work and searching gives me nothing. 

Also, may I humbly suggest that this function gets documented, I found it quite counter intuitive.

**Comment by inukshuk** [comment]
This is not a feature of jekyll-scholar, that's just Ruby programming. The feature of jekyll-scholar is that you can put it in the config file like it says in the Readme with plenty of examples. You're trying to override the defaults with plain Ruby -- it's not documented because it shouldn't be necessary in the first place :-)

Anyway, what you seem to be trying to do in `defaults.rb` is this:

    require 'jekyll/scholar'
    Jekyll::Scholar.defaults['bibtex_skip_fields'] = [:abstract, :month_numeric, :url]

I *think* this is what you want, but you haven't really explained it. If you are not sure then you should probably use the config file instead. That is to say, you don't need a file `_plugins/defaults.rb` but simply put this in your `_config.yml`:

    scholar:
      bibtex_skip_fileds: ["abstract", "month_numeric", "url"]

**Comment by kristiannordestgaard** [comment]
What I want is not to have the URLs from the bibtex files parsed in the HTML. I want the `url =` field completely ignored. 

The latter still parses the URL. Please find attached my full `_config.yml`. 

[_config.txt](https://github.com/inukshuk/jekyll-scholar/files/105168/_config.txt)

**Comment by inukshuk** [comment]
Look, the `bibtex_skip_fields` is used only for the contents of `entry['bibtex']` in your template. I'm not sure what 'URLs being parsed in HTML' is supposed to mean. Do you mean that the URLs show up on your page? If so, where do they show up? In the bibliography? In a citation? On a details page? Scholar doesn't put URLs anywhere by itself: depending on where it shows up it does so either because you put it in your template somewhere or because you are using a citation style that renders URLs if they are present. In the latter case you need to either use a different style or adjust the style to ignore the URL.

**Comment by kristiannordestgaard** [comment]
Thanks, and apologies for being so dense. 

The URLs show up in the bibliography, as shown here on the default "About" page. I have figured out how to adjust the style so it does not show the URLs, but I thought I was doing it in a backwards way. 

Again, thanks for your help. 
![screenshot from 2016-01-26 19 28 24](https://cloud.githubusercontent.com/assets/2007931/12590437/516a105c-c463-11e5-8d1f-1846b1e82077.png)

**Comment by inukshuk** [comment]
Not to worry. In this case it is like I said earlier: your citation style renders the URL there as 'retrieved from'. It looks like you are using APA there, so one option is to download the style and remove this line [here](https://github.com/citation-style-language/styles-distribution/blob/master/apa.csl#L617) (if you want things like DOIs to show up you'd have to edit that macro instead of removing it) and save the style to your computer; then simply set your style to the full path of the file and you'll be using your modified style instead of the original APA one.

**Comment by kristiannordestgaard** [comment]
Thanks, I'll figure it out!

**Comment by mkirchner** [comment]
@kristiannordestgaard has a typo in `_config.yml`: `bibtex_skip_fileds` should be `bibtex_skip_fields`. 

However, @inukshuk, I also fail to get jekyll-scholar to ignore `url` keys that are present in the `.bib` file. Using `bibtex_skip_fields: ["url"]` as above has no effect, and attempting to modify `Jekyll::Scholar.defaults` yields `jekyll 3.1.6 | Error:  can't modify frozen Hash` during `jekyll build`.

Any hints would be much appreciated.

**Comment by inukshuk** [comment]
@mkirchner what are you trying to do? The `bibtex_skip_fields` option is there to remove fields from the bibtex that's exposed to the template a `entry.bibtex`.

You seem to want to remove URLs from the generated reference, is that it? If that's the case, I don't think it is a real issue: your style wants to render URLs and your entry has an URL -- it's perfectly OK to render the URL. If you don't want the URL in the output you should either edit the style, remove the URL from your entry, or pick another style -- either of these three approaches is totally fine, in my opinion.
