### ISSUE TITLE
bibliography_template not used when generating from bibtex file

### ISSUE THREAD

**Issue by edgemaster** [inukshuk/jekyll-scholar#128]
I was hoping to use jekyll-scholar to generate a publications page directly from BibTeX files without requiring supporting pages with `{% bibliography %}` tags.

It seems that the bibtex generator class doesn't make use of the `bibliography_template` option to style the individual bibtex entries.
* Is this intentional or an oversight?
* If I were to submit a PR to enable this behaviour, would it be preferred to use the `bibliography_template` configuration option for this, or to create a new configuration option to maintain backwards compatibility for anyone using the plain rendering style?

**Comment by inukshuk** [comment]
We have basic [BibTeX conversion](https://github.com/inukshuk/jekyll-scholar#bibliographies) enabled by default. For some reasons this is rarely used, but basically it should just convert your BibTeX file straight to HTML (you just need to add the YAML front matter); what's more you can write arbitrary markdown in between your entries (and you could probably add other file endings to run the file through additional converters). I think most people use the bibliography tag because it gives you additional features (like grouping, sorting and so on).

Otherwise, if you want to generate a publications page you would need to add a new Jekyll generator. If I remember correctly we never added this feature because it would call for a means to configure the source bibliography, the path to the generated file, and a way to provide a custom layout and since the same functionality was already covered by the BibTeX converter and the bibliography tag it did not seem to be worth the effort.

I'm not sure which class you refer to as the 'bibtex generator' -- do you mean `BibliographyTag`? If so, that class uses the `bibliography_tag` utility which should make use of the `bibliography_template`.

**Comment by edgemaster** [comment]
Sorry, I meant bibtex converter rather than generator in that paragraph.

Thanks, your reply has made me realise why I shouldn't be using the basic conversion support to generate such a page, namely lack of sorting and grouping functionality.

I'll go with the standard route, sorry for wasting your time and thanks for the support.
