### ISSUE TITLE
controlling formatting of author in details page

### ISSUE THREAD

**Issue by jheidemann** [inukshuk/jekyll-scholar#139]
How does one control the formatting of the author in the details page, and the bibtex-formatted citation?  (On the details page: page.entry.author and page.entry.bibtex.)

Right now names in both places come out inverted, as Lastname, Firstname and Secondlastname, Firstname.
And awkward, that is.  Sounding, Yoda-like.  Something else, I would prefer.

I'm using a modified ACM .csl file and the full, formatted citations do not invert names.
How to I make page.entry.* respect that choice?

Thanks.

**Comment by inukshuk** [comment]
The order or the names in `page.entry.bibtex` is in the normalised in a standard way that is easiest to parse for BibTeX parsers (the last, first syntax has less ambiguities and supports names with multiple last names etc.).

However, you also have access to the individual name parts from the details page via something like `page.entry.author_array[0].last` (i.e., first authors family name).

**Comment by jheidemann** [comment]
About page.entry.author: I though the intent was that this was to be used for presentation to a user.  Shouldn't it therefore be in presentation format?  (I.e., not ugly.)
(But I will try to  work around that problem by formatting the name myself.)

About page.entry.bibtex:  *I* wrote the bibtex entry.  If I disambigutated the names ("Van Meter, Rodney" where "Van Meter" is a two word family name) or not ("Van Jacobson", where "Van" is his given name) presumably I (as the author of the .bib) knew what I was doing.  How can reformatting it improve things?

**Comment by inukshuk** [comment]
There are numerous intents at play here. Some users want to sort the names by last name, for example, and are glad that the names are being parsed, because it is much easier to format a name than to parse it. Most importantly, though, we parse names, because we want to format them with CSL styles which dictate format, order, initials or not, and so on. Since this is an open source effort, however, you are welcome to contribute to combat any perceived ugliness.

Having said that, I am glad to report that you can turn off the `bibtex_option` `parse_names` in your `_config.yml`. Also see #82 because you will probably want to turn off month parsing as well.
