### ISSUE TITLE
Liquid Exception: Unknown tag 'bibliography'

### ISSUE THREAD

**Issue by dpo** [inukshuk/jekyll-scholar#142]
Apologies for a total beginner question. I added the config mentioned in the `README` to my `_config.yml` and my `Gemfile` has
```
source 'https://rubygems.org'

gem 'execjs'
gem 'therubyracer'
gem 'github-pages'
gem 'jekyll-scholar'
```
In `./_bibliography`, I placed `articles2014.bib` and in `publications.md`, I have
```
---
layout: page
title: Publications
---

## 2014

{% bibliography --file articles2014 %}
```
But then
```
$ bundle exec jekyll serve
Configuration file: /Users/dpo/dev/dpo.github.io/_config.yml
            Source: /Users/dpo/dev/dpo.github.io
       Destination: /Users/dpo/dev/dpo.github.io/_site
      Generating... 
  Liquid Exception: Unknown tag 'bibliography' in publications.md
jekyll 2.4.0 | Error:  Unknown tag 'bibliography'
```
Any ideas? Thanks in advance!

**Comment by inukshuk** [comment]
Did you run `bundle install`? (Run `bundle show jekyll-scholar` to ensure it is actually installed.)

Furthermore, you need to make sure the Gem is actually loaded when you run jekyll; normally this is done by requiring it in a Ruby file in your `_plugins` folder or by adding it as a `gem` to your `_config.yml` (see [here](https://github.com/inukshuk/jekyll-scholar#usage)).

**Comment by dpo** [comment]
Thanks! Here's what I have:
```
$ bundle show jekyll-scholar
/Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-4.5.0
```
I added `require 'jekyll/scholar'` to `_plugins/ext.rb` and that resolved something (I thought adding it to the Gemfile achieved the same effect). Now I'm getting:
```
Liquid Exception: Failed to load filter "superscript" in publications.md
```

**Comment by inukshuk** [comment]
You have an old version of scholar installed (current version is 5.7.2). You should either update the gem or remove the 'superscript' filter from your configuration (that filter does not ship with the version you have currently installed).

**Comment by dpo** [comment]
Well, sorry for not knowing much about this but:
```
$ gem install jekyll-scholar
Successfully installed jekyll-scholar-5.7.2
Parsing documentation for jekyll-scholar-5.7.2
1 gem installed
$ bundle show jekyll-scholar
/Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-4.5.0
```
I only installed `jekyll-scholar` yesterday. Is something else forcing usage of an old version?!

**Comment by inukshuk** [comment]
That depends on what other Gems / version you have defined in your Gemfile. You can try to `gem update jekyll-scholar` that will try to install the latest version compatible with your other Gems. My guess is you're still using jekyll 2.x that's why you're stuck on scholar 4.x -- which 'should be fine' (though we're not actively supporting it) if you adjust your configuration (i.e. removing superscript from your config)

**Comment by dpo** [comment]
It works when I remove the superscript filter. I'm not sure what forces the old version. Perhaps `github-pages`? My entire Gemfile is pasted in my original post.

Thanks for the help!

**Comment by edgemaster** [comment]
Aside - I just `bundle install`ed your Gemfile from scratch, which gave me jekyll-scholar 5.7.2.

**Comment by nrenga** [comment]
I had my site working with bibliography till yesterday. Today I was trying to learn Jekyll more carefully and so started from the beginning in the Jekyll docs page. But now when I try to build the same site I had before using "bundle exec jekyll serve" it gives me the error that "unknown tag bibliography found in <file>". One difference today is that I cannot run just "jekyll serve" anymore since doing "bundle update" seems to have introduced gem version differences.

Now I started a fresh simple site as given in the tutorial in Jekyll docs. The only extra thing I added is jekyll-scholar. I have it added under _plugins/ext.rb, the Gemfile and in _config.yml. But even for this simple site when I add "{% bibliography %}, in about.md it throws the above error. What is going wrong?

My Jekyll version is 3.4.3 and my Jekyll Scholar version is 5.8.2. I updated earlier today to 5.10.1 but since I faced this problem, I went back to the previous version I had. Yet the problem remains.

This is what I have at the end of my _config.yml file (my full site folder is attached as .zip):

[learning.zip](https://github.com/inukshuk/jekyll-scholar/files/1117503/learning.zip)

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-scholar
  
scholar:
  style: ieee-with-url
  locale: en

  sort_by: year
  order: descending

  group_by: type
  type_order: thesis,article,inproceedings,techreport
  group_order: none

  source: ./_bibliography
  bibliography: citations.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
