### ISSUE TITLE
Bug in textsuperscript

### ISSUE THREAD

**Issue by dpo** [inukshuk/jekyll-scholar#143]
The regexp used in the `textsuperscript` filter matches the longest string between an opening brace and closing brace. As a result, in the entry
```
@misc{pickaxe,
        title     = {This is \textsuperscript{superscript} and {N}ormal text.}
      }
```
the text `superscript and N` will be superscripted.

Initially, I thought matching the shortest string between braces would fix the bug (it does on the above example), but it still breaks on
```
@misc{pickaxe,
        title     = {\textsuperscript{\"u \"{u} \v{z}}}
      }
```

**Comment by inukshuk** [comment]
IIRC the approach of latex-decode was to match a short string because typically directives that can be expressed with unicode tend to be short (might be wrong though). So I believe the current rationale is, run latex-decode first, remove capitalisation braces in a separate filter (does that happen at the moment?) and finally run superscript: at this point many braces will have been removed already -- and now it's almost a toss-up but matching the shortest string is probably better in most cases (provided the other filters have been run).

That's just mitigation, obviously, but I doubt anyone wants to write a LaTeX parser for this (regular expression matching is not a good approach if you really want to replace nested expressions like this).

@edgemaster do you have any thoughts on the matter?

**Comment by dpo** [comment]
I agree. If other filters have already removed pairs of braces, we're in better shape, although currently, something like `\textsuperscript{\textsf{some} text}` will not be parsed correctly.

**Comment by edgemaster** [comment]
I had previously noticed a similar bug with this filter on one of my own test sites, but wasn't able to reproduce on another version with the same configuration. I have been otherwise engaged, but following this thread with the intention of more closely examining it next week.
