### ISSUE TITLE
First Author's name gets reversed?

### ISSUE THREAD

**Issue by shyamupa** [inukshuk/jekyll-scholar#149]
I want to generate a list of publications page. The markdown for the page looks like,

```
---
layout: default
pagename: Publications
title: Publications
weight: 2
---
{% bibliography --file me %}
```

When I insert the following as the bibtex entry in the me.bib file,

```
@book{ruby,
  title =        {The Ruby Programming Language},
  author =       {Flanagan, David and Matsumoto, Yukihiro},
  year =         {2008},
  publisher =    {O'Reilly Media}
}
```

It renders as

```
Flanagan, David, and Yukihiro Matsumoto. The Ruby Programming Language. O’Reilly Media, 2008. link bibtex
```

The bibtex link at the end looks fine but the list renders the first author's name in reverse. Am I doing something wrong?

**Comment by inukshuk** [comment]
Unless I'm missing something, this looks about right. Name order is controlled by your CSL style, because citation styles often have pretty specific requirements (both for display and for sorting). Most styles will render the first author's family name first in bibliographies -- if you don't want that you need to pick a style which doesn't, or edit your current style ([see here for the gory details](http://docs.citationstyles.org/en/stable/specification.html#name-part-order)).

**Comment by shyamupa** [comment]
I understand CSL style comes into effect if I cite something like,

```
{% cite ruby %}
```
But right now, I am simply generating a list of publications page like [this](http://web.engr.illinois.edu/~upadhya3/publications.html).
Does CSL also apply there? (I am not sure anymore)

**Comment by inukshuk** [comment]
In jekyll-scholar you have full control over the template used for bibliographies; the crucial component is the `reference` string which is rendered by citeproc-ruby according to your CSL style. However, all the individual fields are also exposed to the reference template, so you can omit the `reference` and format your own style. That's only a good idea if you have only very similar references, otherwise I'd rely on the CSL style and adjust the style accordingly. In your case, it should be a very easy adjustment.

**Comment by shyamupa** [comment]
Fixing name-sort-order="" solved it!
