### ISSUE TITLE
URLs in citations again

### ISSUE THREAD

**Issue by rich-d-wilkinson** [inukshuk/jekyll-scholar#158]
I'm having trouble with getting URLs to appear in citations. A reference such as

```
@article{Name,
  website={http://www.facebook.com}
}
```

produces the following line in the html

```
<li><a href="[http://www.facebook.com](http://www.facebook.com)" target="_blank">Website</a></li>
```

which isn't a valid link. I can't understand why the [ ] and ( ) appear in the href.  Any help would be greatly appreciated.

**Comment by inukshuk** [comment]
See discussion at #130 

One of our default filters converts URLs to markdown links: because jekyll-scholar assumes that your pages use markdown these would automatically turn into proper links.

If you don't use markdown (or don't want links), you can disable the filter, by specifying your own filter list in your configuration. Something like this is the default setting:

```
scholar:
  bibtex_filters:
    - latex
    - markdown
```

So you would use that but remove the `- markdown` line.

Alternatively, you could [adjust the filter to create HTML links](https://github.com/inukshuk/jekyll-scholar/issues/30#issuecomment-102004203) (not markdown).

**Comment by rich-d-wilkinson** [comment]
Many thanks. I assume you mean issue #30, which I had read, but struggled to make anything from it work  (I'm learning Ruby as I go). Changing the filter as you suggested did the trick. Thanks.
