### ISSUE TITLE
Option to handle double number from IEEE

### ISSUE THREAD

**Issue by adinriv** [inukshuk/jekyll-scholar#160]
I see that there has been this issue [before](https://github.com/inukshuk/jekyll-scholar/issues/75), but it wasn't solve. It was regarded as a feature from CSL style. However, from the [CSL style perspective](https://github.com/citation-style-language/styles/pull/1970#issuecomment-205507120), it is a problem of the jekyll-scholar team for setting it with numbers instead of using theirs.

As the style may not change because it depends on the definition from the IEEE. Would it be possible to have an option to hide the default numbering? Something like the solution suggested in [issue 75](https://github.com/inukshuk/jekyll-scholar/issues/75), but automatic and out of the box?

**Comment by mamoll** [comment]
Can't you just fix this with some CSS? I have this in my CSS:
```
ol.bibliography { list-style-type: none; padding: 0px; margin: 0px; }
```

**Comment by JoostvanPinxten** [comment]
That would not have the numbers properly aligned...

I hacked around it last time, and I'll share what I used for the reference building:
``{% if site.scholar.style == "ieee" %}
{% comment %}
    This is a hack to remove the reference number from the entry in 
    case 'ieee' style is used to format the reference.
    
    The <span> is repaired by splitting on both the [ and the ] sign.
{% endcomment %}
{%assign ref = reference | split: "]" %}
{%assign pre_num = ref[0] | split:"[" %}
{% for item in pre_num limit:1 %}{{item}}{% endfor %}{% for item in ref offset:1 %}{% if forloop.first == false %}]{% endif %}{{item}}{% endfor %}
{% else %}
{{reference}}
{% endif %}```

And the style:
```
{% if site.scholar.style == "ieee" %}
/* Turn off the numbered items for the IEEE style list */
ol.bibliography li {
	list-style-type:none;
   
}
ol.bibliography li + li { /* 10px between each two adjacent li's */
    margin-top: 10px;
}
ol.bibliography { counter-reset: item }
ol.bibliography li:before { 
    content: "[" counter(item) "] "; 
    counter-increment: item; 
    width:3em;
    position:absolute;
    text-indent:-2em;

}
{% endif %}
```

**Comment by inukshuk** [comment]
I don't really understand what the problem. CSL offers a few parameters to manipulate the bibliography style -- I think that all of these parameters are easy to reproduce with CSS (more so if you adjust the template), therefore, we decided to render all styles in an `ol` by default. jekyll-scholar is used for websites and so most users will already have some CSS rules in place and it should be easy to adjust the list's appearance accordingly.

Double citation numbers happen if the style puts a number into the reference. I don't see how this is an issue however, because you can: turn off the list number with CSS, turn off the citation number in the CSL style (or use a different style) -- those are perfectly fine configuration options, I'm really curious what kind of setting you would expect that would make this easier?

@JoostvanPinxten I would just remove [this line](https://github.com/citation-style-language/styles/blob/master/ieee.csl#L228) from the IEEE style if you want to get rid of the citation numbers.

**Comment by drscotthawley** [comment]
This happens not only for IEEE, but other numbered styles as well. 
Re. "just fix this with some CSS": It would be helpful to know where this CSS is supposed to go.  
I tried adding the code to `_site/assets/style.css` but it keeps getting overwritten when I restart the blog.

**Comment by sentient06** [comment]
Well, I'm sorry, but this is supposed to be easy. Yet it is not.  inukshuk suggests one find a different style. Well, did you try doing that? Look at this thing: https://github.com/citation-style-language/styles
The list is so massive, GitHub is truncating it.

It would be easier if we could simply add a parameter like..

`{% bibliography --suppress_numbering %}`

Can that be done?
