### ISSUE TITLE
`{{` in .bib file incorrectly parsed as liquid code

### ISSUE THREAD

**Issue by mamoll** [inukshuk/jekyll-scholar#168]
I have BibTeX entries with fields like these:
```
journal={{IEEE} Trans.\ on Robotics}
```
This is now resulting in errors like these:
```
 Liquid Exception: Liquid syntax error (line 1): Variable '{{IEEE}' was not properly terminated with regexp: /\}\}/ in publications-bytype.md
```
This used to work.

**Comment by JoostvanPinxten** [comment]
This is due most probably due to my recent merge: https://github.com/inukshuk/jekyll-scholar/pull/167 as the liquid syntax conflicts with the latex entries.  This should be fixed by using `use_raw_bibtex_entry: true` to stop liquid from processing the bibtex.

@inukshuk should we now update the default raw entry to true? This was the old behavior for bibliography tags, and as it is now synced, it might cause these issues

**Comment by inukshuk** [comment]
Yes, we should do that -- it's probably the saner default anyway, because most regular users would not put liquid into their bibtex, right?

**Comment by inukshuk** [comment]
@mamoll starting with 5.8.4 we've changed the default.
