### ISSUE TITLE
Match full name or how to handle common last names

### ISSUE THREAD

**Issue by abelsiqueira** [inukshuk/jekyll-scholar#189]
I'm having a problem with common last for the authors, so that when I do a query, it returns the wrong authors:
```ruby
{% bibliography --query @*[author ~= Doe] %}
```
```
[1] Doe, J. ...
[2] Doe, R. ...
```

I tried matching more of the name, but nothing worked. Any suggestions?
*Great tool, by the way*

**Comment by inukshuk** [comment]
Yes, this is a little tricky.

For context, we're using [bibtex-ruby queries](https://github.com/inukshuk/bibtex-ruby#queries) -- bibtex-ruby actually offers you Ruby's full enumerable interface for the bibliography so you can write very complex queries. Passing a string is intended as a short cut for trivial queries there; in jekyll-scholar you define the queries in a context file so all we support there directly is strings (i.e., just the trivial interface). For more complex queries I always assumed you would just write the query in in Ruby.

Having said that, I think you can write the query you need as a string, it's just a bit tricky because of the idiosyncratic nature of the query 'language'.

That said, here is what happens with your query: the conditions inside the square brackets are split by by `,` (OR) and `&&` (AND) -- and each condition is interpreted as a regular expression and checked for a match against the respective values interpreted as strings. The 'author' field is a names field; by default jekyll-scholar will parse and normalize your names. When they are compared for a match they are converted to a string again so you need to be aware that as far as query matching is concerned something like this happens to the names: `J. Doe and Doe, R.` will be normalized to `Doe, J. and Doe, R.` -- i.e., names will always be matched with the family name first.

Now, what does that mean in your case? You can't use a comma, currently, but when using `~=` your query is interpreted as a regular expression and you can do something like this:

     {% bibliography --query @*[author ~= Doe. J] %}

This would match "Doe, J." anywhere in your author list (i.e. also if it is the second or third author) but not "Doe, R.". It would, however, match something like "Some, Doer J. and Other, G." -- but again, more precise queries would have to be written in Ruby (where you'd have access to match against individual parts of the name etc.).

**Comment by abelsiqueira** [comment]
I didn't realize I can't use `,`, that was my problem.
What you suggested worked for me, but to really try to avoid the commonalities of the names, I'm using a match for `LastName. FirstName M. N`. I just have to be careful to write all bibtex entries (for that name) using the FirstName instead of only the initials.

Thanks for the help
