### ISSUE TITLE
Feature Request: Add functionality for liquid variables passed in

### ISSUE THREAD

**Issue by nate-wernimont** [inukshuk/jekyll-scholar#191]
Hello,

I am trying to call the following command:

{% reference {{bib-id}} --file {{file}} --style /_data/custom.csl %}

The problem is that it interprets {{bib-id}} and {{file}} as exactly that in text. It doesn't take the value of the variable. Now, this is kind of a liquid problem, but I was wondering if support could be added for it. I have found the following thread that provides solutions to it:

https://stackoverflow.com/questions/7666236/how-to-pass-a-variable-into-a-custom-tag-in-liquid?noredirect=1&lq=1

The problem is that if I were to do it, I would be using my own custom version, which makes things complicated. Would this be a possible feature? Or would you know of another way to do this?

**Comment by inukshuk** [comment]
We actually implemented interpolation for the [query parameter](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L154) (see [usage example here](https://github.com/inukshuk/jekyll-scholar/blob/master/features/bibtex.feature#L281))

Since it is already implemented, we could probably just run other parameters through the [interpolate](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L678) method and it might just…work?

Anybody willing to try this out?

**Comment by rseac** [comment]
Has this been fixed? The basic test below seems to pass ...?

[Basic test for Issue 191](https://github.com/rseac/jekyll-scholar/blob/master/features/191.feature)

**Comment by inukshuk** [comment]
I don't think so: the tests just test for interpolation in keys, which, IIRC has been supported for some time, but not in the `file` parameter.

**Comment by rseac** [comment]
Sorry about that.  How about this: #218

**Comment by inukshuk** [comment]
Looks good!

jekyll-scholar is an 'open' open source project: with your last couple of PRs you've earned commit rights -- let me know if you want to be part of the team!
