### ISSUE TITLE
Citation number different from bibliography number with sorted bibliography

### ISSUE THREAD

**Issue by sdruskat** [inukshuk/jekyll-scholar#205]
Many thanks for a great plugin!

I'm trying to achieve the following for a personal homepage.

- Have a bibliography that lists all publications by `year, month` in descending order. This is easy to achieve:

````yaml
scholar:
  style: _bibliography/ieee-with-url.csl
  sort_by: year, month
  order: descending
  bibliography_template: bib
````
Say this bibliography includes the following publications (again sorted by year, month in descending order):

1. pub4 (2017)
2. pub3b (2016, December)
3. pub3a (2016, January)
4. pub2 (2015)
5. pub1 (2014)

`bib.html` isn't special either:

````html
{{ reference | replace_first: 'A. Uthor', '<b>A. Uthor</b>' }} 
{% if entry.url %}
Available at: <a class="citelink" href="{{ entry.url }}">{{ entry.url }}</a>.
{% endif %}
````

The problem is that when I now cite in the text, e.g., `{% cite pub3b pub2 pub1 %}`, the citations are displayed as **[1], [2], [3]**, whereas -- unless I'm missing something -- they should be displayed as **[2], [4], [5]**.

*Am* I missing something, is this intended behaviour, or a corner case application?

EDIT: I've just added 

````yaml
  group_by: year
  group_order: descending
````

which lets the bibliography keys start from [1] for every single year. So I guess this must be something in the way CSL sorts?

**Comment by inukshuk** [comment]
There are two different mechanisms at play when it comes to sorting: the jekyll-scholar config and your CSL style's sorting rules. Normally, when creating a full bibliography using CSL the style would determine the sorting; since jekyll-scholar was written mainly for personal websites and partial bibliographies we added separate sorting options controlled by the user. Therefore, by using jekyll-scholar's `bibliography` tag you control the sorting defined in the configuration (not the one defined by the CSL style).

What's more, the numbers (1., 2., 3., etc.) in the bibliography are *not* citation numbers, but just the numbering of the HTML list; if you use a citation style with numbers, they will be rendered as part of the reference. Generally, using styles with citation numbers is not the best fit for jekyll-scholar because most of its tools are aimed for citing references from a single bibliography on multiple pages; if you do, then you will probably want to turn off list numbers in your CSS.

CSL styles also define a sort order for multiple citations; when using `cite` with multiple references the style should determine the order -- however, this is currently not implemented (see #198) so the multiple citation are always rendered in the order you pass them to the `cite` tag I believe. (My apologies, this *is* confusing!)

By enabling grouping by year, jekyll-scholar resets the citation number for every year -- this is not part of CSL.
