### ISSUE TITLE
bibtex highlighting of entry.bibtex doesn't work

### ISSUE THREAD

**Issue by mamoll** [inukshuk/jekyll-scholar#208]
I am trying to get raw bibtex to be syntax highlighted. This requires `highlighter:  pygments` in `_config.yml`. This works in `regular' markdown content:
```
{% assign  bib = "@InProceedings{mypaper, author={John Doe}, title={My Title} }" %}
{% highlight bibtex %}{{ bib }}{% endhighlight %}
```
but this doesn't:
```
{% highlight bibtex %}{{entry.bibtex}}{% endhighlight %}
```

**Comment by inukshuk** [comment]
Does highlighting work otherwise in the custom template? `entry.bibtex` is just a string so there is not really anything that can go wrong there (provided the string's content looks fine of course). If `highlight` does not work at all within the template, my guess would be that [we're missing some parameters]( https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L474) when calling the Liquid renderer.

**Comment by mamoll** [comment]
Highlighting works correctly if I put the first code snippet in my publication.html template, but not with the second one. In the second case I see that every line is wrapped in `<span class="c">...</span>`.

**Comment by mamoll** [comment]
It seems that entry.bibtex surrounds the text with `{%raw%}` and `{%endraw%}`. If I set `use_raw_bibtex_entry: false` then I get other errors. How do I get entry.bibtex to run through Liquid and _then_ run the result through pygments?

**Comment by inukshuk** [comment]
Oh, that's true, raw is likely the problem there. Well, IIRC the main reason for using the raw tag are to ensure that double curly brackets which may be present in BibTeX are not interpreted by Liquid. What kind of errors do you get if you turn the raw option off? If you can make sure that there are no double curlies in your data, I think it should be fine to disable it. If that's not the reason, @JoostvanPinxten might be able to help.

**Comment by mamoll** [comment]
With the raw option off, I get exactly the kind of errors you'd expect:
```
/Users/mmoll/.gem/ruby/2.4.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:132:in `raise_missing_variable_terminator': Liquid syntax error (line 1): Variable '{{TEST}' was not properly terminated with regexp: /\}\}/ (Liquid::SyntaxError)
	from /Users/mmoll/.gem/ruby/2.4.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:124:in `create_variable'
	from /Users/mmoll/.gem/ruby/2.4.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:40:in `parse'
	from /Users/mmoll/.gem/ruby/2.4.0/gems/liquid-4.0.0/lib/liquid/document.rb:10:in `parse'
	from /Users/mmoll/.gem/ruby/2.4.0/gems/liquid-4.0.0/lib/liquid/document.rb:5:in `parse'
	from /Users/mmoll/.gem/ruby/2.4.0/gems/liquid-4.0.0/lib/liquid/template.rb:132:in `parse'
	from /Users/mmoll/.gem/ruby/2.4.0/gems/liquid-4.0.0/lib/liquid/template.rb:116:in `parse'
	from /Users/mmoll/.gem/ruby/2.4.0/gems/jekyll-scholar-5.10.2/lib/jekyll/scholar/utilities.rb:474:in `bibliography_tag'
...
```
Inserting a space between the two `{`'s doesn't help. I still get the same error. I guess Jekyll-Scholar strip the whitespace somewhere.

**Comment by JoostvanPinxten** [comment]
This is indeed the same kind of incompatibility with Liquid and Latex that I found when I initialily encountered the double braces problem, which led us to use the raw tag. It seems that you do not necessarly need the curly braces for the bibtex entries. A poor work-around would be to use double-quotes around the field values in the bibtex entry instead of curly braces.

I have thought about using a 'consistent' way to distinguish between liquid tags and escaping in Latex, but I have not found any. There is simply a clash between the tags. It could be fixed by adding a way in the Liquid implementation to change the delimiters to something other than curly braces. Changing it in bibtex seems unlikely ;-)

**Comment by mamoll** [comment]
Surely, there must be a way to escape curly braces in bibtex strings before Liquid is parsing the string?

**Comment by JoostvanPinxten** [comment]
That would break both:

1) bibtex escaping of values
2) liquid parsing of fields

It is indeed a third imperfecft variant, because the content of the {%raw%} part cannot be used inside a liquid tag to highlight, if I understand correctly.

So perhaps we can create a third option, that converts the braces to HTML entities, as suggested [here](https://stackoverflow.com/questions/3330979/outputting-literal-curly-braces-in-liquid-templates).

**Comment by mamoll** [comment]
> A poor work-around would be to use double-quotes around the field values in the bibtex entry instead of curly braces.

The workaround idea doesn't work: double quotes get replaced internally by curly braces somewhere.

**Comment by JoostvanPinxten** [comment]
> The workaround idea doesn't work: double quotes get replaced internally by curly braces somewhere.

Note to self: check my own claims; I'm not too familiair with the project... just a very small piece of it.

It seems then that there is no way to go around this, and we may need to do some escaping during bibtex parsing, and reconstruct in the output string the curly bracse, which should allow for Liquid to execute.

**Comment by inukshuk** [comment]
To default to braces has to be a preference set in `bibtex-ruby` somewhere. I'll take a look!

**Comment by inukshuk** [comment]
I added an option `bibtex_quotes` which allows you to configure which quoting preference to pass to bibtex-ruby. The quotes option is a two-item array to set opening and closing quotes, so you could set it to `['"', '"']` to use double quotes. With that, something like `title = {{S}omething}` would be rendered as `title = "{S}omething"`.

Does that help?

Otherwise we could apply pretty much any pattern replacement [here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L512) -- using HTML entities seems like a good choice, but this probably would break the syntax highlighting?

**Comment by mamoll** [comment]
Not a perfect solution, but that works. Thanks!
