### ISSUE TITLE
Feature request: possible to add copy-bibtex-to-clipboard

### ISSUE THREAD

**Issue by Sciss** [inukshuk/jekyll-scholar#223]
Hello! Great plug-in. Is it possible to render such that for each item there is a possibility for the viewer to get the raw bibtex entry; that is, to provide a simple means for the viewer to copy-and-paste for citation?

**Comment by inukshuk** [comment]
Yes that's possible. You'll need to define a custom reference template that renders the full bibtex so that you can access it from javascript (I'd render it into a hidden span or div or into a data attribute). The bibtex is available to your template as `entry.bibtex`. Also check out related config options (like `use_raw_bibtex_entry` or `bibtex_skip_fields`).

**Comment by Sciss** [comment]
Ok, thanks
