### ISSUE TITLE
\emph in titles not converted

### ISSUE THREAD

**Issue by xvazquezc** [inukshuk/jekyll-scholar#242]
Hi there,

Is there any way to make Jekyll-Scholar to translate `\emph` tags into `<i></i>`?

I have a few references where scientific names appear in the titles. Usually they would be in italics but when exporting my library to BibTeX or BibLaTeX, they become `\emph`, which Jekyll-Scholar can't handle.

I guess that it would be related to this BibTeX-Ruby issue, but no idea how to make use of it
https://github.com/inukshuk/bibtex-ruby/issues/28

Thank you in advance,
Xabi

**Comment by inukshuk** [comment]
Yes, `emph` is not part of the default LaTeX filter of BibTeX-Ruby, because its scope is strictly to convert to unicode not to HTML.

For jekyll-scholar, it's a different story. Happy to merge a dedicated filter for this. You can add one similar to the current subscript and [superscript](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/plugins/superscript.rb) filters; you'd have to add such an `emph` filter and then [enable it by default here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/defaults.rb#L39).

**Comment by xvazquezc** [comment]
@inukshuk in the web I'm testing the `<i>..</i>` HTML tags don't work properly, they are inserted in the code, but they aren't translated properly. I don't know if it's just my case or if it's something more general. 
It happens the same when trying to do the author highlighting with `<b>..</b>` as discussed here:
https://github.com/inukshuk/jekyll-scholar/issues/187#issuecomment-286237256
It did work with `<strong>..</strong>` though

The web is based on this template https://github.com/xvazquezc/markdown-cv

**Comment by inukshuk** [comment]
Can you provide a failing test for what you're seeing? In general, I think this works fine, [judging by this successful test](https://github.com/inukshuk/jekyll-scholar/commit/96c48ca272564e2d40f1af1e76f6f3227f86ef89)

I can think of a couple of reasons how something like this could happen: a) when you process the item with citeproc using HTML output (this is what jekyll-scholar does) and b) when you have additional jekyll plugins processing the page into which you rendered the references. There's an easy way to test if it is the latter case: just insert some HTML tags verbatim in your page where you render the bibliography: if that HTML gets escaped in the final result it's most certainly the processing that happens after jekyll-scholar. In that case you'd have to change the order of processing or find a way to escape/allow HTML in the respective places.

**Comment by xvazquezc** [comment]
Update: it seems that in general, sites using Font Awesome, Academic Icons and similar usually use `<i></i>` to place the icons. And they are pretty much everywhere in Jekyll template sites. Still no idea about `<b></b>`

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

**Comment by antoinentl** [comment]
Thank you @xvazquezc for creating the italics filter, but I have an issue with my BibTeX file: I have some title in french with `é` and the filter seems to dislike it, I have the following error for the word `Musée`:

`Variable '{{Mus{\'e}' was not properly terminated with regexp: /\}\}/`

Perhaps I miss something?

**Comment by xvazquezc** [comment]
Sorry @antoinentl, I haven't experimented with Jekyll at all since then. I wouldn't be able to tell/

**Comment by antoinentl** [comment]
Thanks @xvazquezc, I think it depends on the language of the reference, I think I can solve this issue if I modify all the references which include accents.

**Comment by antoinentl** [comment]
Dear @inukshuk, any idea for the origin of the "`was not properly terminated with regexp: /\}\}/`" problem? I have tested other jekyll-scholar plugins and I have the same issue. Thanks for your time!

**Comment by inukshuk** [comment]
This is either a BibTeX parsing or latex decoding issue. What does that value look like exactly in your BibTeX file?

**Comment by antoinentl** [comment]
Here an example:

```
@book{rosso_image_2006,
  address = {{Paris}},
  series = {{Arch{\'e}ologie et histoire de l'art}},
  title = {{L'image de l'empereur en Gaule romaine :  portraits et inscriptions}},
  isbn = {978-2-7355-0583-8},
  lccn = {Tolbiac - Rez de Jardin - Philosophie, histoire, sciences de l'homme - Magasin - 2006-174258},
  shorttitle = {{L'image de l'empereur en Gaule romaine}},
  language = {fre},
  number = {20},
  publisher = {{{\'E}d. du Comit{\'e} des travaux historiques et scientifiques}},
  author = {Rosso, Emmanuelle},
  year = {2006},
  keywords = {Empereurs,Inscriptions latines,Sculpture de portraits romaine},
  note = {ill., couv. ill. 27 cm. Ouvrage issu des m{\'e}moires de ma{\^i}trise et de DEA. Bibliogr. p. 561-582. Notes bibliogr.}
}
```

**Comment by antoinentl** [comment]
Ok @inukshuk It was an exportation problem, I don't understand if it was a format choice or Zotero, but I fix it with a Better BibLaTeX export. Many thanks for your indication :pray:

**Comment by inukshuk** [comment]
I just added your example to our tests and it seems fine.

However, I think I know how to reproduce the problem: if you use your example in a BibTeX  file that is fully converted (i.e., not using the BibTeX file as your 'source' for references and using the `bibliography`, `cite` and other tags accordingly) then you would run into this, because the whole file is, in that case, treated as a liquid template. If you then have double braces anywhere liquid will interpret those as liquid tags and -- in this case complain about missing closing braces, because of the nesting (even if the parsing succeeds, the results would not be what you intended). The only workaround there is to avoid double braces. BibTeX allows to use double quotes around values, which would remove most cases of double braces, but probably not all of them. But anyway, you were probably not even using your BibTeX file in this way (I just looked and this usage is not even documented; I doubt it's used much). Perhaps your BibTeX file was located somewhere in your site folder structure where jekyll found it and tried to convert it?

All that said, if you have double braces in your reference source file this shouldn't be a problem. (see the commit above for an example)
