### ISSUE TITLE
LaTeX-formated citations not rendering

### ISSUE THREAD

**Issue by victoriastuart** [inukshuk/jekyll-scholar#247]
Using jekyll-scholar with LaTeX -formatted citations  (in JabRef, symlinked to `./_bibliography/references.bib`), such as

```
@PhdThesis{stuart1999influences,
  author    = {Stuart, Gregory Roy},
  title     = {Influences of Ageing and Diet on Mutational Frequency and Specificity in Big Blue\textsuperscript{\tiny\textregistered} \textit{lacI} Transgenic Rodents},
  school    = {University of Victoria},
  year      = {1999},
  owner     = {vstuart},
  timestamp = {2014.05.26},
}
```

rendering in Jekyll as

```Stuart, G. R. (1999). Influences of Ageing and Diet on Mutational Frequency and Specificity in Big Blue\tiny\textregistered \textitlacI Transgenic Rodents (PhD thesis). University of Victoria.```

_config.yml

```
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll/scholar
```

Gemfile

```gem 'jekyll-scholar'```

Note references 3 & 5 in screenshot.

![selection_450](https://user-images.githubusercontent.com/2575920/46618083-6a972280-cad3-11e8-885a-1000acf4f527.png)

**Comment by inukshuk** [comment]
Jekyll-Scholar does not support the full set of LaTeX commands; by default, only directives which can be rendered in Unicode are converted. Since Jekyll-Scholar normally renders to HTML (or Markdown) there are a number of simple plugins to convert additional directives (at the moment these include subscript, superscript, emph).

I'm happy to merge plugins covering additional commands such as `\textregistered`, `\tiny`, etc. which translate well to HTML.

**Comment by elotroalex** [comment]
I would add to this list for whoever adds the pr anything that respects `{\lowercase{s}ample}`

**Comment by rseac** [comment]
@inukshuk This could be closed.
