### ISSUE TITLE
Suggestion: details link tag

### ISSUE THREAD

**Issue by nickswalker** [inukshuk/jekyll-scholar#291]
Jekyll's [recommended internal linking style](https://jekyllrb.com/docs/liquid/tags/#links) now looks like this now:

    [Link to a post]({% link _posts/2016-07-26-name-of-post.md %})

It would be nice to have a tag similar to `cite_details` but which simply produces the URL to the details page, so that detail links could be written in a similar way

    [Link to a details page]({% link_details author2020key %})

**Comment by inukshuk** [comment]
Good idea! So this `link_details` tag would just produce the link, right? This should be easy to do, because we already have the [`details_link_for(entry)`](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L608) utility method -- the tag would only have to fetch the corresponding entry and use that method to get the URL.

**Comment by nickswalker** [comment]
Yes, it'll just output the link. I'll draft a PR for this the next time I work on my site.
