### ISSUE TITLE
Failed to parse BibTeX on value: url, note, howpublished? 

### ISSUE THREAD

**Issue by drscotthawley** [inukshuk/jekyll-scholar#308]
The README page seems to give the impression that "url" is a valid BibTeX field to use, i.e., the section about  Filters says, 

> By default, Jekyll-Scholar includes all entries in you main BibTeX file when generating bibliographies. 
> ...
> query: "@*[url]" #=> includes all entries with a url field

but I get an error `Liquid Exception: Failed to parse BibTeX on value "url" (NAME) ...` for any url fields in my `references.bib` entries.

And rather than just ignoring the unrecognized field, it completely fails and the blog won't build at all until I remove the url entry completely.   This failure seems nonstandard; [BibTeX typically ignores unrecognized fields](https://tex.stackexchange.com/questions/21709/comments-in-bibtex).

For example, with `url = {http://www.google.com},`

Trying the [usual alternatives](https://texfaq.org/FAQ-citeURL#:~:text=Bibliographies-,URLs%20in%20BibTeX%20bibliographies,long%2Dawaited%20BibTeX%20version%201.0.) of `howpublished = ` and `note = ` produce similar errors for those keywords.  Trying to enclose the urls in quotes instead of curly braces has no effect.  

How are we to include URLs?

**Comment by inukshuk** [comment]
You're right, BibTeX typiically ignores non-standard fields, which is why such fields are often used for extended functionality. Using `url` fields should work fine; the `howpublished` field is converted for citing purposes: by default to CSL's `publisher` field, but if the field's value looks like a single URL it's converted to CSL's `URL` field.

We definitely have `url` fields in [some test cases](https://github.com/inukshuk/jekyll-scholar/blob/master/features/filter.feature#L157) so this should really work in general. Can you post a minimal example to reproduce the error?

**Comment by DavidWalz** [comment]
@drscotthawley I was following your [guide](https://drscotthawley.github.io/devblog4/2020/07/01/Citations-Via-Bibtex.html) and the `url` field is actually showing up in my case, c.f.
https://davidwalz.github.io/fastpages/markdown/2020/01/14/test-markdown-post.html#citations
https://github.com/DavidWalz/fastpages/blob/master/_bibliography/references.bib

**Comment by drscotthawley** [comment]
Gentelmen, thank you both.  This error seems to have been an artifact of my initial attempts to get the jekyll-scholar up and running on my local machine, in which I had resorted to 'overkill'.  I had added a `_plugins/ext.rb` file on my laptop, but not on the guide that David referred to.  

Indeed I too am able to add the url fields to the guide page. 

Doing a `$ rm ext.rb` on my laptop allows my local instance of my blog to rebuild with the urls!  Thanks. 

Closing this Issue.
