### ISSUE TITLE
References appear as bib

### ISSUE THREAD

**Issue by KonVas** [inukshuk/jekyll-scholar#315]
Hello, I just started using this awesome lib and looking forwrd of deploying it for my publications. I managed to make it work, no significant errors after some tweaking in my github pages, just that it renders the entries as bib.
1. bib
2. bib
3. bib
4. bib
5. bib

> and using {% bibliography_count -f bibliography --query @article[year <=2020] %} I get
"2"

You can see that at the end I can also get the number of the entries corresponding to a specific year, so it kind of works on this end. My bibliography.bib file seems to compile correctly when importing to other formating platforms. 

My yaml config below 

scholar:
```
  style: modern-language-association
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: bibliography.bib

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*" 

```
And my md file from which I callback the bibliography file

```
---
Title: publications
layout: default
permalink: /publications/
---
{% bibliography %}
```
Finally, this is how I render all the above in my front end `default.html` file of my website.

**Comment by inukshuk** [comment]
I don't see anything here that jumps out. You have not posted the `bibliography.bib` file, though I doubt that it is the culprit here. Generally speaking, I'd try to reduce your example further to figure out what's causing this. You could also do this the other way around and start with a minimal setup, [for example as described here in one of our test cases](https://github.com/inukshuk/jekyll-scholar/blob/master/features/page_config.feature), and start adding to it.
