### ISSUE TITLE
Add space after index in IEEE style

### ISSUE THREAD

**Issue by kaustabpal** [inukshuk/jekyll-scholar#340]
I am using ```ieee``` style. 
Currently the references are displayed as ```[1]A. Kirillov, K. He, R. Girshick, C. Rother, and P. Dollar, “Panoptic Segmentation,” Jun. 2019.```
I want to add a space after the ```[1]``` so that it is displayed as ```[1] A. Kirillov, K. He, R. Girshick, C. Rother, and P. Dollar, “Panoptic Segmentation,” Jun. 2019.```. Kindly tell me how to do that?

**Comment by inukshuk** [comment]
I believe this is because we're rendering the references individually and this style adds the spacing via the `second-field-align` attribute for the entire bibliography.

A quick solution to insert a single space would be to add a space to the citation-number suffix `]` in [`ieee.csl`](https://github.com/citation-style-language/styles-distribution/blob/master/ieee.csl#L281) and use your altered style instead.

**Comment by kaustabpal** [comment]
How do I implement this? I can understand that I can add a space to the citation-number suffix ```]```  in [ieee.csl](https://github.com/citation-style-language/styles-distribution/blob/master/ieee.csl#L281) but that is a separate repo. How will making a change there reflect on my page?

**Comment by inukshuk** [comment]
You can reference the style using its full path (instead of just filename without `.csl`), so you can keep a local copy in your site's repository and use that.

**Comment by kaustabpal** [comment]
Got it. Thanks a lot.
