### ISSUE TITLE
Scoping issues with jekyll-scholar and liquid

### ISSUE THREAD

**Issue by davidchisnall** [inukshuk/jekyll-scholar#70]
The functionality to provide custom templates is very helpful, but is somewhat crippled by two (possibly related) issues:

- None of the global Jekyll state objects (site, page) are visible from within that template.
- Plugins (e.g. liquid filter plugins) aren't accessible from that template.  I would like, for example, to use a liquid filter plugin that does regex substitutions to clean up some of the CSL output, but the regex_replace method is never invoked (this is annoying to debug, because there's also no error, it just silently fails).

**Comment by iiegn** [comment]
for anyone ending up here after debugging 'silently failing' filters; to activate the jekyll filters see https://gist.github.com/iiegn/9784826af4b44bba93d1 (i think, the jekyll and the jekyll-scholar world won't fall apart but still, use with care).

**Comment by inukshuk** [comment]
do you see any downside to making this the default behaviour? we'd just have to add a test to guard against regressions, but otherwise this looks good to me.

**Comment by iiegn** [comment]
no, i don't see any but i wanted to be cautious. still, what i don't see straight away is what the 'regression test' would test for...

**Comment by inukshuk** [comment]
I meant just a simple test to ensure that a jekyll filter is actually applied. I referred to it as a regression test, because I use the tests in jekyll-scholar primarily to protect against regressions: over time a lot of features have been added by different people, so if I or somebody else who does not rely on the filters in their own project changes the template code in the future, or if jekyll changes their filter implementation, a simple test will make us aware of the issue.

**Comment by iiegn** [comment]
ok, now i understand: i was thinking about 'what if' people relied on the jekyll filter *not* being available... there, i couldn't really see how to proceed. anyway, this - now to me, too - makes sense!
