### ISSUE TITLE
Numbered citation styles show duplicate numbers

### ISSUE THREAD

**Issue by cameronraysmith** [inukshuk/jekyll-scholar#81]
When I compile with any citation style that provides numbered citations, such as proceedings-of-the-royal-society-b.csl, I get duplicate numbers like this

> 1.  1.Peirce, C. S. 1893 Evolutionary Love. Monist 3, 176–200.(doi:10.5840/monist18933235)
> 2. 2.Peirce, C. S. 1891 The Architecture of Theories. Monist 1, 161–176. (doi:10.5840/monist18911211)

Is this expected behavior or a bug?

**Comment by inukshuk** [comment]
Ah, yes, indeed, it is expected behaviour: the second number is the citation number generated by the style; the first number is simply rendered by your browser because jekyll-scholar puts the references into an HTML ordered list as a semantic preference. You can configure a different reference tag or adjust your CSS to remove the HTML numbers if you don't need them, or, if your style already prints numbers.
