### ISSUE TITLE
cited doesn't mix with prefix

### ISSUE THREAD

**Issue by jheidemann** [inukshuk/jekyll-scholar#90]
This test case explains and demos the bug:

```
---
title: bug demo
---

Mixing multiple bibliographies per page --cited and --prefix
doesn't work.  The --cited are per-page, not per-prefix.

## section one

great work {% cite Quan13c --prefix one %}

And this bibliography will list it:

{% bibliography --cited --prefix one %}

## section two

More great work {% cite Quan14c --prefix two %}

but bibliography will list it BOTH of them.

{% bibliography --cited --prefix two %}

Expected result: cited is per-prefix, so the second bib should list 
the second paper only.
```

**Comment by inukshuk** [comment]
Thanks for reporting!

I've adjusted the bibliography tag to clear cited items automatically in order to support your scenario. All tests pass, but since this changes the behaviour significantly we may have to revert this if there are any complaints. In that case, I suggest we add a new tag that allows you to clear the cited items -- but I hope that won't be necessary.

With this change, if you use `--cited` the cited keys will be cleared automatically; therefore, you can use it just once.

**Comment by inukshuk** [comment]
Landed in 4.5.0

**Comment by jheidemann** [comment]
Yes, that fixes it.  Thanks for the very quick turn-around!

**Comment by inukshuk** [comment]
FYI we reverted back to the old default behavior in 6.3.1. To make the examples above work you can pass the additional `--clear` switch along with `--cited` whenever you want to clear the references after using them.

**Comment by JonathanVacher** [comment]
Hi and thanks for adding this feature !
I might have notice a small bug related to the `--clear` tag and the html numbering.
Here is an example:

```
**Title 1**

{% cite Ref1  --prefix A1 %}
{% cite Ref2  --prefix A1 %}
{% cite Ref3  --prefix A1 %}

References:
{% bibliography --cited --prefix A1 --clear %}

**Title 2**

{% cite Ref2  --prefix B1 %}
{% cite Ref4  --prefix B1 %}

References:
{% bibliography --cited --prefix B1 --clear %}
```

You see here that `Ref2` is referenced 2 times and as the references are cleared and printed in order of appearance the number of `Ref2` changes from 2 to 1. This is correctly updated in the reference list B1 but not in the text where `{% cite Ref2  --prefix B1 %}` will appear as 2 instead of 1.

**Comment by inukshuk** [comment]
What do you mean exactly by 'it will appear as 2 instead of 1' in the text? The `cite` should create an anchor tag with `href="#B1-Ref2"` and the text content is determined by your citation style; the bibliography, by default is marked up as an `ol`; your stylesheet can control whether or not to display the numbering the order in the list is not used as an identifier by the style (some styles make use of citation ids and also print them; in those cases you would definitely need to disable the HTML numbers).
